### ISSUE TITLE
The cells are too wide on Safari

### ISSUE THREAD

**Issue by katemenkhaus** [PredixDev/px-datetime-common#13]
Expected 
![screen shot 2017-07-21 at 2 21 35 pm](https://user-images.githubusercontent.com/14931112/28483014-fd11d9aa-6e1f-11e7-9f5f-1c631d82999a.png)

The bug on Safari
![screen shot 2017-07-21 at 2 19 08 pm](https://user-images.githubusercontent.com/14931112/28483025-0924a0ec-6e20-11e7-91c6-f2360025105a.png)

This bug only occurs on first load. The issue is that when we go to measure the text before the font has loaded the fallback font for canvas is broken on safari (https://forums.developer.apple.com/thread/74980). 
After the font has been cached we can correctly measure the text.

**Comment by randyaskin** [comment]
Appears to have been fixed in Q4'17 refactor
