### ISSUE TITLE
Null pointer exceptions when templating

### ISSUE THREAD

**Issue by alump** [PredixDev/px-datetime-common#18]
In px-datetime-behaviour.html, is this correct:
```javascript
     _localeChangedTemp: function() {
      if(this.language !== undefined && this.momentObj) {
        this.set('_tempMomentObj', this._tempMomentObj.locale(Px.moment.locale()));
      }
    },
```

This can now cause null pointer exception when ```this._tempMomentObj``` is ```null```. This is breaking our demos in some cases when running on one server (some timing issue).

Should it check ```this._tempMomentObj```, not ```this.momentObj```?

**Comment by katemenkhaus** [comment]
fixed in v3.0.1 of px-datetime-common
