### ISSUE TITLE
`listeners` property should be an object expression

### ISSUE THREAD

**Issue by davidsteinberger** [PredixDev/px-datetime-common#5]
## Expected behavior and actual behavior:

The behavior defined in _px-datetime-range-behavior.html_ sets up a listener in an unspecified/undocumented way. It shall be updated to use an object expression as described in the [polymer specs](https://www.polymer-project.org/1.0/docs/devguide/events).

    listeners: [
        '_notifyRangeChanged(range.*)'  // has to become '<<< event >>>': '<<< handler >>>'
    ]

## Steps to reproduce the problem:

NA

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

all versions

**Comment by nonmetalhail** [comment]
My guess is it was supposed to be an observer and not a listener. I'm making that change and removing the observe from the range property declaration. Fixed in v0.7.6.
