### ISSUE TITLE
px-datetime-common.html Missing imports

### ISSUE THREAD

**Issue by trjst89** [PredixDev/px-datetime-common#6]
Hello,

I have px-datetime-common imported in my project; but the browser was not able to find the following files: 
     1.) px-time-input.html
     2.) px-time-rangepicker.html

I looked in the root directory of the px-datetime-common project and do not see px-time-input.html and px-time-rangepicker.html. 

px-datetime-common.html is what requires the imports and it's referencing them as though they are inside of root dir: 
<link rel="import" href="px-datetime-entry.html" />
<link rel="import" href="px-datetime-entry-cell.html" />
<link rel="import" href="px-datetime-buttons.html" />
<link rel="import" href="px-datetime-imports.html" />
<link rel="import" href="px-datetime-presets.html" />
<link rel="import" href="px-time-input.html" />
<link rel="import" href="px-time-rangepicker.html" />
<link rel="import" href="px-datetime-behavior.html" />
<link rel="import" href="px-datetime-range-behavior.html" />

I assume that px-time-rangepicker.html and px-time-input.html need to be added to the root dir of the project. 

Thank you.

**Comment by Menkhaus-ge** [comment]
Hi @trjst89, 

Thank you for bring this to our attention.  
Turns out that px-time-input and px-time-rangepicker were legacy css files. 
I have removed them in v0.7.7. 
This will fix your issue. 

Thanks
